# Site settings
title: Code-sparks
email: darienmt@yahoo.com
description: > 
  Technically yet another blog regarding code, technology, all new and old.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://darienmt.com" # the base hostname & protocol for your site

author:
  fullname: Darien Martinez Torres
  github: darienmt
  # twitter: 
  disqus: darienmt

# Build settings
markdown: kramdown
